---
title: "DHL complete"
author: "Me"
date: "1/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(elastic)
library(elasticsearchr)
library(jsonlite)
library(tidyverse)
library(tidyr)
library(broom)
library(data.table)
library(lubridate)
library(getPass)

conn = connect(
host = "tmsuite-elasticsearch.trackme.com.ph",
port = 443,
path = NULL,
transport_schema = "https",
user = 'jfcastaneda',
pwd =  getPass("Enter Password:"),
headers = NULL,
cainfo = NULL,
force = FALSE,
errors = "simple",
warn = TRUE
)
```

Get the data

```{r}
query = "{\"size\": 10000, \"query\": {\"bool\": {\"must\": [], \"filter\": [{\"bool\": {\"filter\": [{\"nested\": {\"path\": \"pickups\", \"query\": {\"bool\": {\"should\": [{\"exists\": {\"field\": \"pickups.actual_arrival\"}}], \"minimum_should_match\": 1}}, \"score_mode\": \"none\"}}, {\"nested\": {\"path\": \"dropoffs\", \"query\": {\"bool\": {\"should\": [{\"exists\": {\"field\": \"dropoffs.actual_arrival\"}}], \"minimum_should_match\": 1}}, \"score_mode\": \"none\"}}]}}, {\"match_phrase\": {\"group_names\": \"DHL\"}}, {\"range\": {\"created\": {\"gte\": \"2020-10-06T07:49:08.842Z\", \"lte\": \"2021-01-04T07:49:08.842Z\", \"format\": \"strict_date_optional_time\"}}}], \"should\": [], \"must_not\": []}}}"


data = Search(conn, index = 'tmsuite_booking*', body = query, , raw = TRUE)

dhl_data = fromJSON(data)

dhl_data = dhl_data$hits$hits$`_source`

dhl_data = dhl_data %>%
      as.data.table()

head(dhl_data)
```

```{r}
dhl_data = dhl_data %>%
   select(trip_number, vehicle_plate_no, dropoffs, pickups)


dhl_data = dhl_data %>%
   unnest_wider(dropoffs,names_repair = tidyr_legacy) %>%
   unnest_wider(pickups, names_repair =  tidyr_legacy)

dhl_data = dhl_data %>%
   mutate(trip_number = trip_number, 
          vehicle_plate_no = vehicle_plate_no, 
          dropoff_status = status_code,
          dropoff_location = name,
          dropoff_arrival = coalesce(actual_arrival, arrival),
          pickup_status = status_code1,
          pickup_location = name1,
          pickup_arrival = coalesce(actual_arrival1, arrival1),
          .keep =  'none')

```




- Select cols
- distinct values
```{r}

dhl_data = dhl_data %>%
   select(trip_number, pickup_location,dropoff_status, dropoff_location , pickup_arrival, dropoff_arrival, vehicle_plate_no)

dhl_data = dhl_data %>% distinct()

#dhl2 = dhl2 %>%
#   distinct(pickup_location, dropoff_location, .keep_all = T)
```

- convert data
- add rank
- change pickup to be zero
- add next location and dropoff series
- add month and day

```{r}

dhl_data = dhl_data %>%
    gather(key = 'logistic_type', 'location', pickup_location, dropoff_location) %>%
    group_by(trip_number) %>%
   distinct(location, .keep_all = T) %>%
   group_by(trip_number) %>%
   add_count() %>%
   arrange(desc(n), trip_number, desc(logistic_type))


dhl_data = dhl_data %>%
      mutate(arrival = ifelse(logistic_type == 'pickup_location', pickup_arrival, dropoff_arrival)) %>%
      select(-pickup_arrival, -dropoff_arrival)

dhl_data = dhl_data %>% 
   mutate(arrival = ymd_hms(arrival)) %>%
   group_by(trip_number) %>%
   mutate(dropoff_series =rank(arrival, ties.method = 'first'))




dhl_data = dhl_data %>%
   select(trip_number, location, dropoff_series, logistic_type, everything())

dhl_data = dhl_data %>%
      arrange(desc(n), trip_number,dropoff_series)

dhl_data = dhl_data %>%
   mutate(next_location = lead(location),
          dropoff_series = lag(dropoff_series)) %>%
   select(trip_number, location, next_location, dropoff_series, logistic_type, arrival, everything()) %>%
   mutate(dropoff_series = lead(dropoff_series)) %>%
   filter(!is.na(next_location))

dhl_final = dhl_data %>%
   mutate(month = month(arrival),
          day = mday(arrival)) %>%
   select( -logistic_type, -n)

dhl_final %>%
      write_csv('dhl3.csv')
```












