---
title: "Elastic Sample"
author: "Me"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#install elastic search
#load libraries


#connect to server
```{r}
library(elastic)
library(elasticsearchr)
library(jsonlite)
library(tidyverse)
library(tidyr)
library(broom)
library(data.table)
library(lubridate)
library(getPass)

conn = connect(
host = "tmsuite-elasticsearch.trackme.com.ph",
port = 443,
path = NULL,
transport_schema = "https",
user = 'jfcastaneda',
pwd =  getPass("Enter Password:"),
headers = NULL,
cainfo = NULL,
force = FALSE,
errors = "simple",
warn = TRUE
)
```



#Create DHL csv for NEO4j

```{r}
#read data
data = Search(conn, index = 'tmsuite_booking*', size = 10000, q = 'DHL', raw = TRUE)

#convert to Rdata
json_data = fromJSON(data)

#get source
source_dhl = json_data$hits$hits$`_source`

#select cols
dhl_data = source_dhl %>%
   select(trip_number, vehicle_plate_no,vehicle_id, dropoffs, pickups)

#unnest cols
dhl_data= dhl_data %>%
   unnest_wider(dropoffs,names_repair = tidyr_legacy) %>%
   unnest_wider(pickups, names_repair =  tidyr_legacy)

#select and rename cols
dhl_data = dhl_data %>%
   select(trip_number, 
          vehicle_plate_no, 
          vehicle_id,
          dropoff_status = status_code,
          dropoff_location = name,
          dropoff_arrival = arrival,
          pickup_status = status_code1,
          pickup_location = name1,
          pickup_arrival = arrival1)

#unnest other cols
dhl_data = dhl_data %>%
   unnest(pickup_status) %>%
   unnest(pickup_location) %>%
   unnest(pickup_arrival)

#get multiple dropoffs
dhl_data = dhl_data %>%
   group_by(trip_number) %>%
   mutate(unique_pickups = n_distinct(pickup_location),
          unique_dropoffs = n_distinct(dropoff_location)) %>%
   filter(unique_dropoffs > 1)

#convert to date
dhl_data = dhl_data %>%
   select(-unique_dropoffs, -unique_pickups) %>%
   mutate(dropoff_arrival = ymd_hms(dropoff_arrival),
          pickup_arrival = ymd_hms(pickup_arrival))

#select distinct
dhl_data = dhl_data %>%
   distinct()

#rearrange rows
dhl_data = dhl_data %>%
   select( trip_number,pickup_location, pickup_arrival, dropoff_location, dropoff_arrival, everything())

#get distinct pickup and dropoff
dhl_data_distinct = dhl_data %>%
   group_by(trip_number) %>%
   distinct(pickup_location, dropoff_location, .keep_all = T)

#add ranking
dhl_data_distinct = dhl_data_distinct %>%
   select(-dropoff_status, -pickup_status) %>%
   group_by(trip_number) %>%
   mutate(dropoff_series = rank(dropoff_arrival, ties.method = 'first'))

#add month and day
dhl_data_distinct = dhl_data_distinct %>%
   mutate(month_pickup = month(pickup_arrival),
          day_pickup = day(pickup_arrival))

#rename cols and geather
dhl_data_distinct = dhl_data_distinct%>%
   mutate(dropoff_series =  paste0('dropoff_',dropoff_series)) %>%
   mutate(dropoff_time = paste0(dropoff_series, '_time')) %>%
   spread(dropoff_series, dropoff_location) %>%
   select( trip_number,pickup_location, dropoff_1, dropoff_2, dropoff_3, dropoff_4, everything()) %>%
   select(-dropoff_time) %>%
   select(-pickup_arrival, -dropoff_arrival)

#mix into one row
dhl_series = dhl_data_distinct %>%
   group_by(trip_number, pickup_location) %>%
   mutate(dropoff_1 = max(dropoff_1, na.rm = T),
          dropoff_2 = max(dropoff_2, na.rm = T),
          dropoff_3 = max(dropoff_3, na.rm = T),
          dropoff_4 = max(dropoff_4, na.rm = T)) %>%
   distinct()
```






#DHL2 
-Second dataset from ELI

```{r}
#load query
query = "{\"size\": 10000, \"query\": {\"bool\": {\"must\": [], \"filter\": [{\"match_all\": {}}, {\"match_phrase\": {\"group_names\": \"DHL\"}}, {\"range\": {\"created\": {\"gte\": \"2020-11-08T16:00:00.000Z\", \"lte\": \"2020-11-18T15:59:59.000Z\", \"format\": \"strict_date_optional_time\"}}}], \"should\": [], \"must_not\": []}}}"

#search using query
dhl2 = Search(conn, index = 'tmsuite_booking*', body = query, , raw = TRUE)

#convert to list
dhl2 = fromJSON(dhl2)

#get source
dhl2_source = dhl2$hits$hits$`_source`

#select cols
dhl2 = dhl2_source %>%
   select(trip_number, vehicle_plate_no, dropoffs, pickups)

dhl2 = dhl2 %>%
   unnest_wider(dropoffs,names_repair = tidyr_legacy) %>%
   unnest_wider(pickups, names_repair =  tidyr_legacy)

#select and rename cols
dhl2 = dhl2 %>%
   select(trip_number, 
          vehicle_plate_no, 
          dropoff_status = status_code,
          dropoff_location = name,
          dropoff_arrival = arrival,
          pickup_status = status_code1,
          pickup_location = name1,
          pickup_arrival = arrival1)

#unnest
dhl2 = dhl2 %>%
   unnest(pickup_status) %>%
   unnest(pickup_location) %>%
   unnest(pickup_arrival)

#select multiple dropoffs
dhl2 = dhl2 %>%
   group_by(trip_number) %>%
   mutate(unique_pickups = n_distinct(pickup_location),
          unique_dropoffs = n_distinct(dropoff_location)) %>%
   filter(unique_dropoffs > 1)

#convert to date
dhl2 = dhl2 %>%
   select(-unique_dropoffs, -unique_pickups) %>%
   mutate(dropoff_arrival = ymd_hms(dropoff_arrival),
          pickup_arrival = ymd_hms(pickup_arrival))

#select distinct values
dhl2 = dhl2 %>%
   distinct()

#rearrange
dhl2 = dhl2 %>%
   select( trip_number,pickup_location, pickup_arrival, dropoff_location, dropoff_arrival, everything())

#get distinct pickup and dropoff
dhl2 = dhl2 %>%
   group_by(trip_number) %>%
   distinct(pickup_location, dropoff_location, .keep_all = T)

#add rank based on dropoff arrival
dhl2 = dhl2 %>%
   select(-dropoff_status, -pickup_status) %>%
   group_by(trip_number) %>%
   mutate(dropoff_series = rank(dropoff_arrival, ties.method = 'first'))

#mutate dates
dhl2 = dhl2 %>%
   mutate(month_pickup = month(pickup_arrival),
          day_pickup = day(pickup_arrival))

#rearrange cols
dhl2 = dhl2%>%
   mutate(dropoff_series =  paste0('dropoff_',dropoff_series)) %>%
   mutate(dropoff_time = paste0(dropoff_series, '_time')) %>%
   spread(dropoff_series, dropoff_location) %>%
   select( trip_number,pickup_location, dropoff_1, dropoff_2, dropoff_3, dropoff_4, everything()) %>%
   select(-dropoff_time) %>%
   select(-pickup_arrival, -dropoff_arrival)

#select max
dhl2_series = dhl2 %>%
   group_by(trip_number, pickup_location) %>%
   mutate(dropoff_1 = max(dropoff_1, na.rm = T),
          dropoff_2 = max(dropoff_2, na.rm = T),
          dropoff_3 = max(dropoff_3, na.rm = T),
          dropoff_4 = max(dropoff_4, na.rm = T),
          dropoff_5 = max(dropoff_5, na.rm = T),
          dropoff_6 = max(dropoff_6, na.rm = T),
          dropoff_7 = max(dropoff_7, na.rm = T)) %>%
   distinct()



```





#DHL2 new data format
- new dhl dataformat
- not horizontal
- easier transfer from csv to neo4j

```{r}

library(elastic)
library(elasticsearchr)
library(jsonlite)
library(tidyverse)
library(tidyr)
library(broom)
library(data.table)
library(lubridate)
library(getPass)

conn = connect(
host = "tmsuite-elasticsearch.trackme.com.ph",
port = 443,
path = NULL,
transport_schema = "https",
user = 'jfcastaneda',
pwd =  getPass("Enter Password:"),
headers = NULL,
cainfo = NULL,
force = FALSE,
errors = "simple",
warn = TRUE
)

query = "{\"size\": 10000, \"query\": {\"bool\": {\"must\": [], \"filter\": [{\"match_all\": {}}, {\"match_phrase\": {\"group_names\": \"DHL\"}}, {\"range\": {\"created\": {\"gte\": \"2020-11-08T16:00:00.000Z\", \"lte\": \"2020-11-18T15:59:59.000Z\", \"format\": \"strict_date_optional_time\"}}}], \"should\": [], \"must_not\": []}}}"

dhl2 = Search(conn, index = 'tmsuite_booking*', body = query, , raw = TRUE)


dhl2 = fromJSON(dhl2)

dhl2_source = dhl2$hits$hits$`_source`


dhl2 = dhl2_source %>%
   select(trip_number, vehicle_plate_no, dropoffs, pickups)


dhl2 = dhl2 %>%
   unnest_wider(dropoffs,names_repair = tidyr_legacy) %>%
   unnest_wider(pickups, names_repair =  tidyr_legacy)

dhl2 = dhl2 %>%
   select(trip_number, 
          vehicle_plate_no, 
          dropoff_status = status_code,
          dropoff_location = name,
          dropoff_arrival = arrival,
          pickup_status = status_code1,
          pickup_location = name1,
          pickup_arrival = arrival1)

dhl2 = dhl2 %>%
   unnest(pickup_status) %>%
   unnest(pickup_location) %>%
   unnest(pickup_arrival)
```

- Select cols
- distinct values
- 
```{r}
library(lubridate)
dhl2 = dhl2 %>%
   select(trip_number, pickup_location,dropoff_status, dropoff_location , pickup_arrival, dropoff_arrival, vehicle_plate_no)

dhl2 = dhl2 %>% distinct()

dhl2 = dhl2 %>%
   distinct(pickup_location, dropoff_location, .keep_all = T)

```

- convert data
- add rank
- change pickup to be zero
- add next location and dropoff series
- add month and day
```{r}
dhl2= dhl2 %>% 
   mutate(trip_number = as.numeric(trip_number),
          pickup_arrival = ymd_hms(pickup_arrival),
          dropoff_arrival = ymd_hms(dropoff_arrival)) %>%
   group_by(trip_number) %>%
   mutate(dropoff_series =rank(dropoff_arrival, ties.method = 'first'))

dhl_gather = dhl2 %>%
    gather(key = 'logistic_type', 'location', pickup_location, dropoff_location) %>%
    group_by(trip_number) %>%
   distinct(location, .keep_all = T) %>%
   group_by(trip_number) %>%
   add_count() %>%
   arrange(desc(n), trip_number, desc(logistic_type))

dhl_gather = dhl_gather %>%
   mutate(dropoff_series = ifelse(logistic_type== 'pickup_location',0, dropoff_series)) %>%
   select(-n)

dhl_gather = dhl_gather %>%
   select(trip_number, location, dropoff_series, logistic_type, everything())

dhl_gather = dhl_gather %>%
   mutate(next_location = lead(location)) %>%
   select(trip_number, location, next_location, dropoff_series, logistic_type, dropoff_arrival, everything()) %>%
   mutate(dropoff_series = lead(dropoff_series)) %>%
   filter(!is.na(next_location))

dhl_final = dhl_gather %>%
   mutate(month = month(dropoff_arrival),
          day = mday(dropoff_arrival)) %>%
   select(-dropoff_arrival, -logistic_type, -pickup_arrival)

```





















