---
title: "Comparing CICO"
author: "Me"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
ryan_cico = read_csv('Ryan-CICO.csv')
ryan_cico
```

```{r}
trans_cico = read_csv('CICO_FROM_GPS/Transpecial_GPS_CICO_DecToJan_ver2.csv')
pan_cico = read_csv('CICO_FROM_GPS/PAN_GPS_CICO_DecToJan_ver2.csv')
ehd_cico = read_csv('CICO_FROM_GPS/EHD_GPS_CICO_DecToJan_ver2.csv')



ehd_cico %>%
      arrange(first_timestamp)
```

```{r}
ryan_cico = ryan_cico %>%
      arrange(checkin) %>%
      mutate(checkin = checkin + hours(8), 
             checkout = checkout + hours(8))
```

```{r}

fix_duplicates = function(data){
      
      #select only needed cols
      data = data %>%
            select(-time_next) %>%
            arrange(plateno, first_timestamp, geofence_name)
      
      # floor to 1 minute
      # data = data %>%
      #       mutate(first_timestamp = floor_date(first_timestamp, '1 minute'),
      #              last_timestamp = floor_date(last_timestamp, '1 minute'))
      
      
      # Remove continuning
      data = data %>%
            mutate(continuing = if_else(geofence_name == lead(geofence_name) & geofence_name == lag(geofence_name), 1, 0))%>%
            filter(continuing == 0)
      
      data = data %>%
            select(-continuing) %>%
            mutate(has_same_next = ifelse(geofence_name == lead(geofence_name), 1, 0))

      data = data %>%
            mutate(new_last_timestamp = if_else(has_same_next == 1, lead(last_timestamp), last_timestamp)) %>%
            mutate(new_last_timestamp = coalesce(new_last_timestamp, last_timestamp)) %>%
            mutate(to_remove = lag(has_same_next == 1)) %>%
            filter(to_remove != T) %>%
            select(-last_timestamp, -to_remove, -has_same_next) %>%
            rename(last_timestamp = new_last_timestamp)
      
      data = data %>%
             select(plateno, geofence_name, first_timestamp, last_timestamp) %>%
             mutate(last_timestamp = ymd_hms(last_timestamp),
                   first_timestamp = ymd_hms(first_timestamp)) %>%
             mutate(dwell_time = as.duration(last_timestamp - first_timestamp))
            
      return(data)
}

ehd_cico_fixed = fix_duplicates(ehd_cico)
```


# LOAD MARCH CICO

```{r}
ehd_cico = read_csv('ehd_cico_march.csv')
```


```{r}
ehd_cico_fixed %>%
   filter(plateno == 'YJC382')
```

```{r}
ryan_cico %>%
   filter(plateno == 'YJC382')
```


