---
title: "Converting CICO to FO"
author: "Me"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
make_fo = function(data, pattern){
      data = data %>%
            left_join(pattern)
      
      data = data %>%
            select(-last_timestamp) %>%
            rename(entry_time = first_timestamp) %>%
            arrange(plateno, entry_time) %>%
            mutate(source = ifelse(pattern == 1, geofence_name, NA)) %>%
            mutate(source_entrytime = if_else(pattern == 1, as.character(entry_time), NA_character_)) %>%
            group_by(plateno) %>%
            fill(source) %>%
            fill(source_entrytime)
      
        # arrange cols
      data = data %>%
            select(plateno,
                   source_geofence = source,
                   dest_geofence = geofence_name,
                   source_entrytime,
                   dest_entrytime = entry_time,
                   everything())
      
      #remove source geofence and dest geofence
      data = data %>%
            filter(pattern != 1 & !is.na(source_geofence)) %>%
            select( -pattern)    
      
      return(data)
      
}
```

```{r}
data = read_csv('Ryan-CICO.csv')

fo_format = data %>%
      select(-checkout) %>%
      rename(entry_time = checkin,
             geofence_name = location) %>%
      arrange(plateno, entry_time) %>%
      mutate(source = ifelse(pattern == 1, geofence_name, NA)) %>%
      mutate(source_entrytime = if_else(pattern == 1, as.character(entry_time), NA_character_)) %>%
      group_by(plateno) %>%
      fill(source) %>%
      fill(source_entrytime)


  fo_format = fo_format %>%
            select(plateno,
                   source_geofence = source,
                   dest_geofence = geofence_name,
                   source_entrytime,
                   dest_entrytime = entry_time,
                   everything())
```

```{r}
fo_format %>%
      write_csv('Ryan-CICO-Fo-Format.csv')
```

```{r}
normalize_fo = function(data){
      
      normalized = data %>%
            arrange(plateno, source_entrytime) %>%
            group_by(plateno, source_geofence) %>%
            mutate(continuing = if_else(dest_geofence == lag(dest_geofence), 1, 0)) %>%
            filter(continuing == 0 | is.na(continuing)) %>%
            select(-continuing)
      
      normalized = normalized %>%
            mutate(source_entrytime = as.character(source_entrytime),
                   dest_entrytime = as.character(dest_entrytime))
      
      # normalized = normalized %>%
      #       select(-dwell_time)
      
      return(normalized)
      
}

fo_format_normalized = normalize_fo(fo_format)

fo_format_normalized %>%
      write_csv('Ryan-CICO-Fo-Format-Normalized.csv')
```

