---
title: ''
author: "Me"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
data = read_csv('export.csv')
data %>%
      mutate(industry = fct_reorder(industry, total_units)) %>%
      ggplot(aes(industry, total_units, fill = industry))+
      geom_col()+
      coord_flip()
```

```{r}
data = read_csv('export.csv', na = 'null')
data %>%
      mutate(cust_name = fct_reorder(cust_name, units)) %>%
      arrange(desc(units)) %>%
      head(10) %>%
      ggplot(aes(cust_name,units, fill = cust_name)) +
            geom_col()+
            coord_flip()
```

```{r}
neo4j = read_csv('ontime_neo4j.csv')
elastic = read_csv('ontime_elastic.csv')
```
```{r}
neo4j
```
```{r}
elastic %>%
   left_join(neo4j, by = c('trip_number' = 't.trip_number')) %>%
   select(-c(dropoff_arrival, dropoff_actual_arrival,pickup_arrival, pickup_actual_arrival ))
```

```{r}
first_data = read_csv('first_data.csv')
first_data %>%
   anti_join(elastic, by = 'trip_number')
```
```{r}
elastic %>%
   anti_join(neo4j, by = c( 'trip_number' = 't.trip_number'))
```
```{r}
elastic %>%
   distinct(trip_number)
```

