---
title: "Jumping GPS identification"
author: "Me"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries needed
```{r}
library(tidyverse)
library(RPostgreSQL)
library(getPass)
library(lubridate)
library(data.table)
```

Load data
```{r}
trans_data = read_csv('input_data/EHD-GPS-Dec-to-Jan-Formatted-ver2.csv')
trans_data
```

```{r}
head(trans_data)
```


```{r}
format_data = function(data){
      
      data = data %>%
            mutate(datestamp = datestamp + hours(8))
      
      data = data %>%
            select(datestamp, plateno, alert_msgs, longitude, latitude)
      
      #switch long and lat
      data = data %>%
            mutate(longitude_fix = ifelse(longitude < 100, latitude, longitude),
                   latitude_fix = ifelse(latitude > 100, longitude, latitude)) %>%
            select(-longitude, -latitude) %>%
            rename(longitude = longitude_fix, 
                   latitude = latitude_fix)
      
      return(data)
}

formatted_data = format_data(trans_data)
```
Sanity check for time
```{r}
formatted_data %>%
      summarise(min(datestamp),
                max(datestamp))
```

```{r}
dim(formatted_data)
```


Upload to postgis
```{r}
gps_to_postgis = function(data, postgis_table = 'gps_to_postgis_table', userpass, password){
      pgdrv <- dbDriver(drvName = "PostgreSQL")
      
      postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = userpass,
                    password = password)
      
      data = data %>%
            select(-alert_msgs)
      
      data = data %>%
            mutate(datestamp = as.character(datestamp))
      
      dbWriteTable(postgrescon, postgis_table, data, row.names=FALSE, append=TRUE)
}

gps_to_postgis(formatted_data, 'ehd_staging', userpass = 'postgres', password = getPass('Password:'))
```



Query for creating tables in postgresql

CREATE TABLE gps_data
(
    datestamp text,
   	geom geometry(point,4326),
	plateno text
);


INSERT INTO gps_data
SELECT 
	datestamp,
	ST_TRANSFORM(ST_SETSRID(ST_POINT(longitude, latitude), 4326), 4326) AS geom,
	plateno
FROM staging_table



