---
title: "Geofence Library"
author: "Me"
date: "5/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

```{r}
library(tidyverse)
library(lubridate)
library(data.table)
library(ggplot2)
library(plotly)
```

```{r}
geofences = read_csv('TMSUITE-Geofences-asof-0517-Formatted.csv')
geofences = geofences %>%
      select(name, group_names, geofence_code)

```

```{r}
geofences %>%
      count(group_names)
```

```{r}
geofences = geofences %>%
      mutate(group_names_new = ifelse(str_detect(group_names, 'Nestle'), 'Nestle', NA)) %>%
      mutate(group_names_new = ifelse(str_detect(group_names, 'DHL'), 'DHL', group_names_new)) %>%
      mutate(group_names_new = ifelse(str_detect(group_names, 'HAVI'), 'HAVI', group_names_new))
```
`


```{r}
DC = read_csv('Nestle-P-Geofences.csv') 
```

```{r}
geofences_with_dc = geofences %>%
      left_join(DC, by = c('name' = 'Dropoffs')) %>%
      group_by(name) %>%
      distinct() %>%
      mutate(DC = paste0(Pickups, collapse = ' , ' ),
             num_dc = n_distinct(Pickups))



geofences_with_dc = geofences_with_dc %>%
      distinct(name, group_names, group_names_new, geofence_code, DC, num_dc)
```


```{r}
geofences_with_dc = geofences_with_dc %>%
      ungroup() %>%
      mutate(DC = ifelse(DC == 'NA', 'None', DC),
             num_dc = ifelse(DC == 'None', 0, num_dc))
```

```{r}
geofences_with_dc %>%
   arrange(desc(num_dc))   
```

```{r}
no_dc = read_csv('nodcdata_12.csv')
no_dc = no_dc %>%
      select(name, geofence_code)
```

```{r}
no_dc %>%
      mutate(in_geofences_with_dc = .$name %in% geofences_with_dc$name) %>%
      mutate(in_dropoff = .$name %in% DC$Pickups) %>%
      mutate(in_orig_geofence = .$name %in% geofences$name)
```


```{r}
geofences_with_dc %>%
      write_csv('geofences_with_dc.csv')
```

```{r}
geofences_with_dc %>%
      arrange(desc(num_dc)) %>%
      head(50) %>%
      view()
```

