---
title: "Generating CICO for March Data"
author: "Me"
date: "3/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RPostgreSQL)
library(getPass)
library(lubridate)
library(data.table)
```


```{r}
data = read_csv('Nestle_JM0535_April1-April10-Formatted.csv')
data
```


```{r}
data = read_csv('input_data/EHD_Logistics-GPS-Dec-to-Jan-Formatted.csv')
```

```{r}
data
```

```{r}
data %>%
      summarise(min(created), max(created))
```

```{r}
data = data %>%
      rename(datestamp = created)
```



```{r}
format_data = function(data){
      
      # data = data %>%
      #       mutate(datestamp = datestamp + hours(8))
      
      # data = data %>%
      #       mutate(location = str_remove_all(location, "\\{|\\}|\\'|\\:"))

      # data = data %>%
      #        separate(location, into = c('longitude','latitude'), sep = ',')


      data = data %>%
            mutate(longitude = as.numeric(str_extract(longitude, '\\d.*')),
                   latitude = as.numeric(str_extract(latitude,'\\d.*')))

      data = data %>%
            select(datestamp, plateno, longitude, latitude)
      
      #switch long and lat
      data = data %>%
            mutate(longitude_fix = ifelse(longitude < 100, latitude, longitude),
                   latitude_fix = ifelse(latitude > 100, longitude, latitude)) %>%
            select(-longitude, -latitude) %>%
            rename(longitude = longitude_fix, 
                   latitude = latitude_fix)
      
      return(data)
}

formatted_data = format_data(data)
```

```{r}
formatted_data %>%
      summarise(min(datestamp),
                max(datestamp))
```

```{r}

get_entered = function(data){
      
      data = data %>%
      mutate(alert_msgs = str_replace_all(alert_msgs,"\\[|\\]|\\'",''))

      pattern = '(Entered .*)'

      entered_data = data %>%
            mutate(extracted = str_extract_all(alert_msgs, pattern)) %>%
            unnest(extracted) %>%
            separate_rows(alert_msgs, sep =',')


      entered_data = entered_data %>%
            filter(str_detect(alert_msgs,'Entered')) %>%
            mutate(location = str_replace(alert_msgs,'Entered ',''))
      
      entered_data %>%
            arrange(datestamp) %>%
            mutate(datestamp = as.character(datestamp))
      
      entered_data = entered_data %>%
            select(datestamp, plateno, latitude, longitude, location)
      
      return(entered_data)
}
entered_data = get_entered(formatted_data)
```

```{r}
formatted_data
```


## Transfer GPS data to postgis
Transfer GPS data to postgis for spatial analysis

```{r}
gps_to_postgis = function(data, postgis_table = 'gps_to_postgis_table', userpass, password){
      pgdrv <- dbDriver(drvName = "PostgreSQL")
      
      postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = userpass,
                    password = password)
      
      data = data %>%
            mutate(datestamp = as.character(datestamp))
      
      dbWriteTable(postgrescon, postgis_table, data, row.names=FALSE, append=TRUE)
}

gps_to_postgis(formatted_data, 'staging_table', userpass = 'postgres', password = getPass('Password:'))
```


## Transfer GPS data to postgis
Transfer GPS data to postgis for spatial analysis

```{r}
gps_to_postgis = function(data, postgis_table = 'gps_to_postgis_table', userpass, password){
      pgdrv <- dbDriver(drvName = "PostgreSQL")
      
      postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = userpass,
                    password = password)
      
      data = data %>%
            select(-alert_msgs)
      
      data = data %>%
            mutate(datestamp = as.character(datestamp))
      
      dbWriteTable(postgrescon, postgis_table, data, row.names=FALSE, append=TRUE)
}

gps_to_postgis(formatted_data, 'staging_table', userpass = 'postgres', password = getPass('Password:'))
```


# Get points inside geofence.
Get the points inside the geofence.  Make sure that the gps data are in postgis

```{r}
query =  "SELECT
	t.datestamp,
	t.plateno,
	g.name AS geofence_name
FROM 
	gps_data AS t
JOIN
	nestle_geofences_march23 AS g
ON 
      ST_INTERSECTS(g.geom, t.geom);"

get_gps_inside_geofence = function(userpass, password, query){
   pgdrv <- dbDriver(drvName = "PostgreSQL")
   postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = userpass,
                    password = password)
   
   points_in_geofences <- dbGetQuery(postgrescon, query)
 
   points_in_geofences = points_in_geofences %>%
      mutate(datestamp = ymd_hms(datestamp))
      
   points_in_geofences = points_in_geofences %>%
      arrange(datestamp)
     
   return(points_in_geofences)
}

points_inside_geofence = get_gps_inside_geofence(userpass = 'postgres', password = getPass('Password:'), query = query)
```


```{r}
points_inside_geofence %>%
      summarise(min(datestamp), max(datestamp))
```


```{r}
vehicle_location_group = points_inside_geofence %>%
      mutate(track_period = floor_date(datestamp, '30 minutes')) %>%
      group_by(plateno, geofence_name, track_period) %>%
      mutate(time_start = min(datestamp),
             time_end = max(datestamp),
             num_points = n()) %>%
      mutate(duration = as.duration(time_end - time_start)) 
```



```{r}
get_cico = function(points_inside_geofences){
   vehicle_location_group = points_inside_geofence %>%
      mutate(track_period = floor_date(datestamp, '30 minutes')) %>%
      group_by(plateno, geofence_name, track_period) %>%
      mutate(time_start = min(datestamp),
             time_end = max(datestamp),
             num_points = n()) %>%
      mutate(duration = as.duration(time_end - time_start)) 


   #remove passed only
   vehicle_location_group_reduced = vehicle_location_group%>%
         filter(duration  > 300 & num_points > 5) %>%
         arrange(plateno, geofence_name, track_period)
   
   
   vehicle_location_group_reduced = vehicle_location_group_reduced %>%
         select(plateno, geofence_name, track_period, time_start, time_end, duration, num_points)  %>%
         distinct()
   
   morethan5mins = vehicle_location_group_reduced %>%
      arrange(plateno, track_period)

   #Rename column
   morethan5mins = morethan5mins %>%
         rename(duration_period_at_geofence = duration)
   
   #remove initial checking
   morethan5mins = morethan5mins %>%
         group_by(plateno, geofence_name) %>%
         arrange(plateno, geofence_name)
   
   morethan5mins = morethan5mins %>%
      mutate(time_end_previous_location = lag(time_end),
             time_start_next_location = lead(time_start)) %>%
      mutate(time_difference_to_next_location = as.duration(time_start_next_location - time_end),
             time_difference_from_prev_location =as.duration(time_start - time_end_previous_location)) 
   
   morethan5mins = morethan5mins %>%
      select(plateno,
             geofence_name,
             time_start, 
             time_end,
             time_end_previous_location,
             time_start_next_location,
             duration_period_at_geofence,
             time_difference_to_next_location,
             time_difference_from_prev_location,
             everything())
   
   
   morethan5mins = morethan5mins %>%
        mutate(continue_next_location = time_difference_to_next_location < 300,
               contine_prev_location = time_difference_from_prev_location < 300)  %>%
      mutate(continue_both_location = contine_prev_location & continue_next_location)

   #filter out data to record only entry and exit 
   morethan5mins = morethan5mins %>%
      filter(continue_both_location == F | is.na(continue_both_location))
   
   #compute for actual end time
   morethan5mins = morethan5mins %>%
      group_by(plateno, geofence_name) %>%
      mutate(actual_time_end = if_else(
            (is.na(time_end_previous_location) | lead(time_difference_from_prev_location)  < 300) 
            & !(time_difference_to_next_location > 300), 
            lead(time_end),
            time_end
      )) 
   
   
   #filter no actual time end because they are the last for that location
   morethan5mins = morethan5mins %>%
      mutate(actual_time_end = if_else(is.na(time_difference_to_next_location), time_end, actual_time_end))
   
   #select relevant columns
   #compute for duration at geofence
   morethan5mins = morethan5mins%>%
         filter(!is.na(actual_time_end)) %>%
         select(plateno, geofence_name, time_start, actual_time_end) %>%
          mutate(duration_at_geofence = as.duration(actual_time_end - time_start))
   
   #create ranking based on duration
   fixed_data = morethan5mins %>%
         group_by(plateno, geofence_name, actual_time_end) %>%
         mutate(rank = rank(desc(duration_at_geofence)))
   
   
   #remove the last entry
   fixed_data = fixed_data %>%
         filter(rank != 2) 
   
   #ungroup and select cols
   fixed_data = fixed_data %>%
         ungroup() %>%
         select(plateno, 
                geofence_name,
                first_timestamp = time_start, 
                last_timestamp = actual_time_end, 
                time_duration_at_geofence = duration_at_geofence)
   
   fixed_data_arranged = fixed_data %>%
      arrange(plateno, first_timestamp) %>%
      group_by(plateno) %>%
      mutate(time_next = lead(first_timestamp)) %>%
      mutate(time_next = as.duration(time_next - last_timestamp))
   
   fixed_data_arranged = fixed_data_arranged %>%
      arrange(first_timestamp) %>%
      mutate(first_timestamp = as.character(first_timestamp),
             last_timestamp = as.character(last_timestamp)) 
   
   return(fixed_data_arranged)
}

cico_data = get_cico(points_inside_geofence)
```

```{r}
cico_data = cico_data %>%
      rename(dwelltime = time_duration_at_geofence) %>%
      select(-time_next)
```

```{r}
cico_data = cico_data %>%
      rename(datestamp_entry = first_timestamp,
             datestamp_left = last_timestamp)
cico_data %>%
      write_csv('JM0535_cico.csv')
```




```{r}
cico_data %>%
      mutate(first_timestamp = as.character(first_timestamp),
             last_timestamp = as.character(last_timestamp)) %>%
      select(-time_next) %>%
      write_csv('ehd_cico.csv')
```

```{r}
cico_data
```


```{r}
fix_duplicates = function(data){
      
      #select only needed cols
      data = data %>%
            select(-time_next) %>%
            arrange(plateno, first_timestamp, geofence_name)
      
      # floor to 1 minute
      # data = data %>%
      #       mutate(first_timestamp = floor_date(first_timestamp, '1 minute'),
      #              last_timestamp = floor_date(last_timestamp, '1 minute'))
      
      
      # Remove continuning
      data = data %>%
            mutate(continuing = if_else(geofence_name == lead(geofence_name) & geofence_name == lag(geofence_name), 1, 0))%>%
            filter(continuing == 0)
      
      data = data %>%
            select(-continuing) %>%
            mutate(has_same_next = ifelse(geofence_name == lead(geofence_name), 1, 0))

      data = data %>%
            mutate(new_last_timestamp = if_else(has_same_next == 1, lead(last_timestamp), last_timestamp)) %>%
            mutate(new_last_timestamp = coalesce(new_last_timestamp, last_timestamp)) %>%
            mutate(to_remove = lag(has_same_next == 1)) %>%
            filter(to_remove != T) %>%
            select(-last_timestamp, -to_remove, -has_same_next) %>%
            rename(last_timestamp = new_last_timestamp)
      
      data = data %>%
             select(plateno, geofence_name, first_timestamp, last_timestamp) %>%
             mutate(last_timestamp = ymd_hms(last_timestamp),
                   first_timestamp = ymd_hms(first_timestamp)) %>%
             mutate(dwell_time = as.duration(last_timestamp - first_timestamp))
            
      return(data)
}

normalized_cico = fix_duplicates(cico_data)
```


```{r}
normalized_cico %>%
      mutate(first_timestamp = as.character(first_timestamp),
             last_timestamp = as.character(last_timestamp)) %>%
      write_csv('normalized_march_cico.csv')
```

















