---
title: "Create new CICO using New geofence"
author: "Me"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries needed
```{r}
library(tidyverse)
library(RPostgreSQL)
library(getPass)
library(lubridate)
library(data.table)
```


```{r}
query =  "SELECT 
	t.datestamp,
	t.plateno,
	g.name AS geofence_name
FROM 
	nestle_geofences_march23 AS g
INNER JOIN
	ehd_gps_data AS t
ON ST_INTERSECTS(g.geom , t.geom)"

get_gps_inside_geofence = function(userpass, password, query){
   pgdrv <- dbDriver(drvName = "PostgreSQL")
   postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = userpass,
                    password = password)
   
   points_in_geofences <- dbGetQuery(postgrescon, query)
 
   points_in_geofences = points_in_geofences %>%
      mutate(datestamp = ymd_hms(datestamp))
      
   points_in_geofences = points_in_geofences %>%
      arrange(datestamp)
     
   return(points_in_geofences)
}

points_inside_geofence = get_gps_inside_geofence(userpass = 'postgres', password = getPass('Password:'), query = query)
```


```{r}
get_cico = function(points_inside_geofences){
   vehicle_location_group = points_inside_geofence %>%
      mutate(track_period = floor_date(datestamp, '30 minutes')) %>%
      group_by(plateno, geofence_name, track_period) %>%
      mutate(time_start = min(datestamp),
             time_end = max(datestamp),
             num_points = n()) %>%
      mutate(duration = as.duration(time_end - time_start)) 


   #remove passed only
   vehicle_location_group_reduced = vehicle_location_group%>%
         filter(duration  > 300 & num_points > 5) %>%
         arrange(plateno, geofence_name, track_period)
   
   
   vehicle_location_group_reduced = vehicle_location_group_reduced %>%
         select(plateno, geofence_name, track_period, time_start, time_end, duration, num_points)  %>%
         distinct()
   
   morethan5mins = vehicle_location_group_reduced %>%
      arrange(plateno, track_period)

   #Rename column
   morethan5mins = morethan5mins %>%
         rename(duration_period_at_geofence = duration)
   
   #remove initial checking
   morethan5mins = morethan5mins %>%
         group_by(plateno, geofence_name) %>%
         arrange(plateno, geofence_name)
   
   morethan5mins = morethan5mins %>%
      mutate(time_end_previous_location = lag(time_end),
             time_start_next_location = lead(time_start)) %>%
      mutate(time_difference_to_next_location = as.duration(time_start_next_location - time_end),
             time_difference_from_prev_location =as.duration(time_start - time_end_previous_location)) 
   
   morethan5mins = morethan5mins %>%
      select(plateno,
             geofence_name,
             time_start, 
             time_end,
             time_end_previous_location,
             time_start_next_location,
             duration_period_at_geofence,
             time_difference_to_next_location,
             time_difference_from_prev_location,
             everything())
   
   
   morethan5mins = morethan5mins %>%
        mutate(continue_next_location = time_difference_to_next_location < 300,
               contine_prev_location = time_difference_from_prev_location < 300)  %>%
      mutate(continue_both_location = contine_prev_location & continue_next_location)

   #filter out data to record only entry and exit 
   morethan5mins = morethan5mins %>%
      filter(continue_both_location == F | is.na(continue_both_location))
   
   #compute for actual end time
   morethan5mins = morethan5mins %>%
      group_by(plateno, geofence_name) %>%
      mutate(actual_time_end = if_else(
            (is.na(time_end_previous_location) | lead(time_difference_from_prev_location)  < 300) 
            & !(time_difference_to_next_location > 300), 
            lead(time_end),
            time_end
      )) 
   
   
   morethan5mins = morethan5mins %>%
      mutate(actual_time_end = if_else(is.na(time_difference_to_next_location), time_end, actual_time_end))
   #filter no actual time end because they are the last for that location
   #select relevant columns
   #compute for duration at geofence
   morethan5mins = morethan5mins%>%
         filter(!is.na(actual_time_end)) %>%
         select(plateno, geofence_name, time_start, actual_time_end) %>%
          mutate(duration_at_geofence = as.duration(actual_time_end - time_start))
   
   #create ranking based on duration
   fixed_data = morethan5mins %>%
         group_by(plateno, geofence_name, actual_time_end) %>%
         mutate(rank = rank(desc(duration_at_geofence)))
   
   
   #remove the last entry
   fixed_data = fixed_data %>%
         filter(rank != 2) 
   
   #ungroup and select cols
   fixed_data = fixed_data %>%
         ungroup() %>%
         select(plateno, 
                geofence_name,
                first_timestamp = time_start, 
                last_timestamp = actual_time_end, 
                time_duration_at_geofence = duration_at_geofence)
   
   fixed_data_arranged = fixed_data %>%
      arrange(plateno, first_timestamp) %>%
      group_by(plateno) %>%
      mutate(time_next = lead(first_timestamp)) %>%
      mutate(time_next = as.duration(time_next - last_timestamp))
   
   fixed_data_arranged = fixed_data_arranged %>%
      arrange(first_timestamp) %>%
      mutate(first_timestamp = as.character(first_timestamp),
             last_timestamp = as.character(last_timestamp)) 
   
   return(fixed_data_arranged)
}

cico_data = get_cico(points_inside_geofence)
```

```{r}
   vehicle_location_group = points_inside_geofence %>%
      mutate(track_period = floor_date(datestamp, '30 minutes')) %>%
      group_by(plateno, geofence_name, track_period) %>%
      mutate(time_start = min(datestamp),
             time_end = max(datestamp),
             num_points = n()) %>%
      mutate(duration = as.duration(time_end - time_start)) 
```


```{r}
vehicle_location_group %>%
      filter(plateno == 'RMP262')
```


```{r}
cico_data %>%
      select(-time_next) %>%
      write_csv('ehd_cico_march.csv')
```

