---
title: "Matching FO with all points"
author: "Me"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
trans_fo = read_csv('data for matching all points/trans_fo.csv')

trans_fo = trans_fo %>%
      filter(complete.cases(.))

trans_fo = trans_fo %>%
      arrange(trip_number)
```

#fix trans_fo to have a sequence of locations format
```{r}
trans_fo_gathered = trans_fo %>%
      gather(pickup_name, dropoff_name,
             key = 'location_type', value = 'geofence_name') %>%
      gather(pickup_arrival, dropoff_arrival, key = 'time_type', value = 'arrival') %>%
      arrange(trip_number) %>%
      filter((location_type == 'pickup_name' & time_type == 'pickup_arrival') | (location_type == 'dropoff_name' & time_type == 'dropoff_arrival')) %>%
      select(-time_type)
```

#load all points inside geofence
```{r}
points_group = read_csv('data for matching all points/points_grouped_processed.csv')
points_group
```

#manipulate FO data to remove seconds
```{r}
trans_fo_gathered = trans_fo_gathered %>%
      mutate(arrival = round_date(arrival, '1 minute'))
```

#Matched if the bookings are inside the geofences

```{r}
matched = trans_fo_gathered %>%
      left_join(points_group, by = c('geofence_name' = 'geofence_name', 'vehicle_plate_no' = 'plateno', 'arrival' = 'datestamp')) %>%
      filter(!is.na(track_period))
```



```{r}
trans_fo_gathered %>%
      left_join(matched) %>%
      arrange(trip_number) %>%
      filter(trip_number %in% matched$trip_number)
```

