---
title: "Transferring CICO Generated Data to Neo4j"
author: "Me"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

Load the data
```{r}
data = read_csv('For Ham/TranspecialDecJan_CICO_FromGPS.csv')
data = data %>%
      arrange(plateno)
```

Create into neo4j format
```{r}
processed_data = data %>%
      select(-time_next, -last_timestamp) %>%
      group_by(plateno) %>%
      mutate(next_geofence = lead(geofence_name)) %>%
      select(plateno, 
             geofence = geofence_name,
             next_geofence,
             entry = first_timestamp,
             everything()) %>%
      mutate(loc1_datestamp = entry, 
             loc2_datestamp = lead(entry)) %>%
      select(-entry)

processed_data = processed_data %>%
      filter(!is.na(next_geofence))
```

```{r}
processed_data %>%
      mutate(loc1_datestamp = as.character(loc1_datestamp),
             loc2_datestamp = as.character(loc2_datestamp)) %>%
      write_csv('transpecial_cico_to_neo4j.csv')
```


