---
title: "Measuring Travel Distance"
author: "Me"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)
library(RPostgreSQL)
library(getPass)
```

## Measuring distance using POSTGIS ST_DISTANCE FUNCTION

```{r}
wide_area_travel = read_csv('wide_area_travels_analysis.csv')
```

```{r}
wide_area_travel = wide_area_travel %>%
        filter(complete.cases(.))
```

```{r}
wide_area_travel = wide_area_travel %>%
        janitor::clean_names()
```

```{r}
wide_area_travel = wide_area_travel %>%
        separate(origin_center, into = c('origin_lat','origin_long'), sep = ',') %>%
        mutate(origin_lat = as.numeric(origin_lat),
               origin_long = as.numeric(origin_long)) %>%
        separate(destination_center, into = c('destination_lat','destination_long'), sep = ',') %>%
        mutate(destination_lat = as.numeric(destination_lat),
               destination_long = as.numeric(destination_long))
```

```{r}
wide_area_travel
```


# Upload to postgres
```{r}
pgdrv <- dbDriver(drvName = "PostgreSQL")
postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = 'postgres',
                    password = getPass('Password:'))


dbWriteTable(postgrescon, 'wide_area_travel', wide_area_travel, row.names=FALSE, append=TRUE)
```

```{r}
wide_area_travel = read_csv('wide_area_travel.csv')
wide_area_travel = wide_area_travel %>%
        filter(complete.cases(.))

wide_area_travel
```

```{r}
wide_area_original = read_csv('wide_area_travels_analysis.csv')
points = wide_area_original %>%
        janitor::clean_names() %>%
        filter(complete.cases(.)) %>%
        select(origin_points, destination_points)
```

```{r}
wide_area_travel$destination_points = points$destination_points
wide_area_travel$origin_points = points$origin_points
```


```{r}
query = 'SELECT *,
        ST_DISTANCESPHERE(ST_TRANSFORM(ST_SETSRID(ST_POINT(origin_long, origin_lat), 4326), 4326),
        ST_TRANSFORM(ST_SETSRID(ST_POINT(destination_long, destination_lat), 4326), 4326))/1000 AS distance_st
        FROM wide_area_travel'

pgdrv <- dbDriver(drvName = "PostgreSQL")
postgrescon <-DBI::dbConnect(pgdrv,
                    dbname="WTI",
                    host="localhost", port=5432,
                    user = 'postgres',
                    password = getPass('Password:'))


wide_area_travel = dbGetQuery(postgrescon, query)
```

### With measured distance from 

```{r}
wide_area_travel = read_csv('wide_area_travel_withOSMdist.csv')
```

```{r}
wide_area_travel = wide_area_travel %>%
        select(-WKT,-destination_points, -'gis-id', -distance_OSM_m)
```

```{r}
wide_area_travel = wide_area_travel %>%
        mutate(origin_coord = paste0(origin_lat, ',', origin_long )) %>%
        mutate(destination_coord = paste0(destination_lat, ',', destination_long)) %>%
        select(-origin_lat, -origin_long, -destination_lat, -destination_long)
```

```{r}
wide_area_travel = wide_area_travel %>%
        select(vehicle, startstamp, stopstamp, origin, destination, orig_category, dest_category, group_name, travel_duration, distance_traveled, straight_distance=  distance_st, distance_OSM = distance_OSM_km)
```

```{r}
wide_area_travel %>%
        filter(origin == destination)
```


```{r}
wide_area_travel = wide_area_travel %>%
        filter(origin != destination) %>%
        mutate(ST_ratio = distance_traveled/straight_distance,
               OSM_ratio = distance_traveled/distance_OSM) %>%
        arrange(ST_ratio)
```

```{r}
wide_area_travel = wide_area_travel %>%
        mutate(startstamp = as.character(ymd_hms(startstamp) - hours(16)),
               stopstamp = as.character(ymd_hms(stopstamp) - hours(16))) 

```

```{r}
wide_area_travel = wide_area_travel %>%
        mutate(distance_traveled_cat = cut(distance_traveled, breaks = c(0,100,250,500,1000,2000),
                                           labels = c('0-100','100-250','250-500','500-1000','1000+'))) %>%
        mutate(OSM_ratio_cat = cut(OSM_ratio, breaks = c(0, .8, 1.5, 2, 2.5, 3,5, 10, 100, 100000), 
                                   labels = c('0 - 0.8','0.8 - 1.5','1.5 - 2','2 - 2.5','2.5 - 3','3 - 5','5 - 10', '10 - 100','100+')))
```


```{r}
wide_area_travel %>%
        ggplot(aes(OSM_ratio_cat))+
        geom_bar(stat = 'count', fill = 'steelblue')+
        facet_wrap(~ distance_traveled_cat)
```

```{r}
wide_area_travel %>%
        filter(distance_traveled_cat == '500-1000') %>%
        arrange(OSM_ratio)
```

