---
title: "ver 3 verification"
author: "Me"
date: "3/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

# Normalized data

#load data

```{r}
full_match_norm = read_csv('normalized-data/full_match.csv')
assumed_match_norm = read_csv('normalized-data/partial_match.csv')
no_match_norm = read_csv('normalized-data/no_match.csv')
all_cico_norm = read_csv('normalized-data/normalized_pan_cico_fo_ver1.csv')
pan_fo = read_csv('normalized-data/pan_fo.csv')
head(all_cico_norm)
```


```{r}
dim(all_cico_norm)
dim(no_match_norm)
dim(full_match_norm)
dim(assumed_match_norm)
```


```{r}
full_match_norm$type = 'full_match'
assumed_match_norm$type = 'assumed_match'

all_matches_norm = full_match_norm %>%
      rbind(assumed_match_norm)
```

```{r}
all_matches_with_cico_match = all_cico_norm %>%
      semi_join(all_matches_norm, by = c('plateno' = 'CICO-vehicle', 'source_geofence' = 'pickups_name', 
                                    'dest_geofence' = 'dropoffs_name', 'source_entrytime' = 'CICO-time-Pickup', 'dest_entrytime' = 'CICO-time-Dropoff'))

all_matches_norm %>%
      semi_join(all_matches_with_cico_match, by = c('CICO-vehicle' = 'plateno',
                                                    'pickups_name' = 'source_geofence',
                                                    'dropoffs_name' = 'dest_geofence',
                                                    'CICO-time-Pickup' = 'source_entrytime',
                                                    'CICO-time-Dropoff' = 'dest_entrytime'))

```
```{r}
all_matches_norm %>%
      group_by(`CICO-vehicle`) %>%
      summarise(n = n()) %>%
      arrange(desc(n))

all_matches_norm %>%
      filter(`CICO-vehicle` == 'CAA3065')
```
1 CICO matched with two FO


```{r}
# fo = fo %>%
#       mutate(dropoff_arrival = dropoff_arrival - hours(8),
#              pickup_arrival = pickup_arrival - hours(8))

fo_nomatch = pan_fo %>%
      anti_join(all_matches_norm, by = c('trip_number' = 'trip_number',
                                    'vehicle_plate_no' = 'vehicle_plate_no',
                                    'so_number' = 'so_number',
                                    'dropoff_name' = 'dropoffs_name',
                                    'dropoff_arrival' = 'dropoffs_arrival',
                                    'pickup_name' = 'pickups_name',
                                    'pickup_arrival' = 'pickups_arrival'))
```


```{r}
no_match_norm %>%
      left_join(fo_nomatch, by = c('plateno' = 'vehicle_plate_no', 
                                   'source_geofence' = 'pickup_name', 
                                   'dest_geofence' = 'dropoff_name')) %>%
      filter(complete.cases(.))
```

# Non normalized data

Load non normalized data
```{r}
full_match_non = read_csv('non-normalized-data/full_match.csv')
assumed_match_non = read_csv('non-normalized-data/assumed_match.csv')
no_match_non = read_csv('non-normalized-data/no_match.csv')
all_cico_non = read_csv('non-normalized-data/non_normalized_cico.csv')

head(all_cico_non)
```
```{r}
dim(full_match_non)
dim(assumed_match_non)
dim(no_match_non)
```

## processing non normalized cico data
```{r}
raw_cico_non = read_csv('non-normalized-data/raw_cico.csv')
all_cico_non = raw_cico_non %>%
      rename(source_geofence = source,
             dest_geofence = geofence_name,
             source_entrytime = source_first_timestamp,
             dest_entrytime = first_timestamp) %>%
      filter(!is.na(source_geofence)) %>%
      filter(pattern != 1) %>%
      select(plateno, source_geofence, dest_geofence, source_entrytime, dest_entrytime)

```


## Check total of match and non match is equal to FO
```{r}
full_match_non$type = 'full_match'
assumed_match_non$type = 'assumed_match'

all_match_non = assumed_match_non %>%
   rbind(full_match_non)

all_cico_non %>%
   semi_join(all_match_non, by = c('plateno' = 'CICO-vehicle',
                                   'source_geofence' = 'pickups_name',
                                   'dest_geofence' = 'dropoffs_name',
                                   'source_entrytime' = 'CICO-time-Pickup',
                                   'dest_entrytime' = 'CICO-time-Dropoff')) %>%
   group_by(plateno) %>%
   summarise(n = n()) %>%
   arrange(desc(n))
```
```{r}
all_match_non %>%
   group_by(`CICO-vehicle`) %>%
   summarise(n = n()) %>%
   arrange(desc(n))

all_match_non %>%
   filter(`CICO-vehicle` == 'CAA3065')
```
Doubled CICOs
- CBB1680
- CBJ1142
- CAA3065


# get the difference between matched on normalized and matched on non normalized
```{r}
all_match_non %>%
   anti_join(all_matches_norm) %>%
   group_by(pickups_name, dropoffs_name) %>%
   summarise(n = n())

```

#check results or compare with CICO
```{r}

```

















