---
title: "Matching Algo Results Presentation"
author: "Me"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lubridate)
library(ggplot2)
library(tidyverse)
library(scales)
```

```{r}
data = read_csv('transpecial_matched.csv')
data = data %>%
      mutate(diff_pickup = pickup_arrival - source_entry_time,
             diff_dropoff = dropoff_arrival - dest_entry_time)
```

```{r}
data = data %>%
      mutate(diff_pickup_num = parse_number(as.character(diff_pickup))) %>%
      mutate(diff_dropoff_num = parse_number(as.character(diff_dropoff)))
```


```{r}
data %>%
      rename(pickup = diff_pickup_num,
             dropoff = diff_dropoff_num) %>%
      gather(pickup, dropoff, key = 'type', value = 'diff_time') %>%
      filter((abs(diff_time/86400)) < 10) %>%
      ggplot(aes(diff_time/86400, fill = type)) +
      geom_histogram(binwidth = .5)+
      scale_x_continuous(breaks = c(-25,-20,-10,-7,-3,-1,1, 3, 7, 10, 20, 25))+
      labs(x = 'Time difference (day)',
           y = '',
           fill = '',
           title = 'Time difference between FO and CICO')+
      theme_minimal()
```


