---
title: "Processing transpecial ver 2 points in geofences"
author: "Me"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RPostgreSQL)
library(getPass)
library(lubridate)
library(data.table)
```

```{r}
points_in_geofences = read_csv('transpecial_ver2_points_in_geofences.csv')

points_in_geofences %>%
      summarise(min(datestamp),
                max(datestamp))
```



```{r}
points_group = points_in_geofences %>%
      mutate(datestamp = ymd_hms(datestamp)) %>%
      mutate(track_period = floor_date(datestamp, '30 minutes')) %>%
      group_by(plateno, geofence_name, track_period) %>%
      mutate(time_start = min(datestamp),
             time_end = max(datestamp),
             num_points = n()) %>%
      mutate(duration = as.duration(time_end - time_start))
```

```{r}
points_group_processed = points_group %>%
      mutate(datestamp = round_date(datestamp,'1 minute')) %>%
      distinct()

points_group_processed %>%
      mutate(track_period = as.character(track_period),
             time_start = as.character(time_start),
             time_end = as.character(time_end),
             datestamp = as.character(datestamp)) %>%
      write_csv('points_grouped_processed.csv')
```

