---
title: "Titanic Pt2"
author: "Me"
date: "10/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
library(ggplot2)
theme_set(theme_light())
```

```{r}
train = read_csv('train.csv')
test = read_csv('test.csv')
train %>%
  view()
```

```{r}
str(train)
str(test)
```

```{r}
nearZeroVar(train)
numeric_cols = map_lgl(train, is.numeric)
train[,numeric_cols]
```

```{r}
map_dbl(train %>% select(-Survived), function(x) sum(is.na(x)))
map_dbl(test, function(x) sum(is.na(x)))
```

```{r}
train %>%
 filter(is.na(Age)) %>%
  ggplot(aes(as.factor(Survived)))+
  geom_bar()+
  labs(title= 'Distribution of Survived for those passengers with missing Age')
```

Check cabin data
```{r}
train %>%
  count(has_cabin = !is.na(Cabin))
```


Try to complete training data
```{r}
train_model = train %>%
  select(-PassengerId, -Name, -Ticket) %>%
  mutate(Survived = as.factor(Survived),
         Pclass = as.factor(Pclass),
         Sex = as.factor(Sex),
         SibSp = as.factor(SibSp),
         Parch = as.factor(Parch),
         Embarked = as.factor(Embarked)) %>%
  mutate(Cabin = factor(ifelse(!is.na(Cabin), 1, 0)))
train_model
```

To run models faster
```{r}
library(doParallel)
#Find out how many cores are available (if you don't already know)
cores<-detectCores()
#Create cluster with desired number of cores, leave one open for the machine         
#core processes
cl <- makeCluster(cores[1]-1)
#Register cluster
registerDoParallel(cl)
```

```{r}
impute_preprocess = preProcess(as.data.frame(train_model), method = 'knnImpute')
train_model_preproc = predict(impute_preprocess, as.data.frame(train_model))
train_model_preproc[is.na(train_model_preproc %>% select(Embarked)),'Embarked'] = 'S'
train_model_preproc
```


```{r}
map_dbl(train_model_preproc %>% select(-Survived), function(x) sum(is.na(x)))
```

```{r}
hist(train_model_preproc[,'Fare'])
```

```{r}
train_model_preproc
```

Modeling

```{r}
ctrl = trainControl(summaryFunction = twoClassSummary, 
                    classProbs = T, 
                    method = 'repeatedcv',
                    repeats = 5)

c50Grid <- expand.grid(trials = c(1:9, (1:10)*10),
                       model = c("tree", "rules"),
                       winnow = c(TRUE, FALSE))
```

```{r}
train_model_preproc
```

```{r}
levels(train_model_preproc$Survived)
```

Try C5.0 model
```{r}
set.seed(476)
C50_tune <- train(make.names(Survived) ~., data = train_model_preproc,
                      method = "C5.0",
                      tuneGrid = c50Grid,
                      verbose = FALSE,
                      metric = "ROC",
                      trControl = ctrl)
```


```{r}
C50_tune$finalModel
```

```{r}
test_model = test%>%
  select(-PassengerId, -Name, -Ticket) %>%
  mutate(Pclass = as.factor(Pclass),
         Sex = as.factor(Sex),
         SibSp = as.factor(SibSp),
         Parch = as.factor(Parch),
         Embarked = as.factor(Embarked)) %>%
  mutate(Cabin = factor(ifelse(!is.na(Cabin), 1, 0)))
  
```

```{r}
impute_preprocess_test = preProcess(as.data.frame(test_model), method = 'knnImpute')

test_model_preproc = predict(impute_preprocess_test, as.data.frame(test_model))
map_dbl(test_model_preproc, function(x) sum(is.na(x)))
```

```{r}
test_model_preproc
```

```{r}
train_model_preproc %>%
  count(Parch)
```

```{r}
test_model_preproc %>%
  count(Parch)
```

```{r}
test_model_preproc[test_model_preproc$Parch==9,'Parch'] = 6
```


```{r}
test_preds = predict(C50_tune, test_model_preproc)
test_preds = ifelse(test_preds == 'X0',0,1)
```

```{r}
my_submission3 = read.csv('my_submission2.csv')

my_submission3 = my_submission3 %>%
  mutate(Survived_1 = test_preds)
```
```{r}
table(my_submission3$Survived, my_submission3$Survived_1)
```

```{r}
my_submission3 = my_submission3 %>%
  mutate(Survived = Survived_1) %>%
  select(-Survived_1)

write_csv(my_submission3, 'my_submission3.csv')
```








